title: Abishek Krishnan # your name (or website title) here
logo: "/images/Dubare_Photo_Edited.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  3+ years of software engineering experience. Pursuing a Master's in Computer Science from the University of Utah.
  <br><br>
  Currently, looking for full-time software engineering roles starting May-2021.
  <br>
  <a href="https://www.linkedin.com/in/abishek-krishnan-9a423512a/">LinkedIn</a>
theme: jekyll-theme-minimal
